CREATE TABLE IF NOT EXISTS USER(
    ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    CLIENT_NAME     VARCHAR(50),
    ROLE     VARCHAR(50),
    EMAIL    VARCHAR(100),
    PASSWORD VARCHAR(400),
    ENABLED  BOOLEAN NOT NULL DEFAULT 0
    );
