CREATE TABLE IF NOT EXISTS COMMENT (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    REVIEW_ID INT NOT NULL,
    SELLER_ID INT NOT NULL,
    FOREIGN KEY (REVIEW_ID) REFERENCES REVIEW(ID),
    FOREIGN KEY (SELLER_ID) REFERENCES SELLER(ID)
    )