CREATE TABLE IF NOT EXISTS address(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    SELLER_ID INT,
    STREET VARCHAR(255),
    WARD VARCHAR(255),
    DISTRICT VARCHAR(255),
    CITY VARCHAR(255),
    FOREIGN KEY (USER_ID) REFERENCES user(ID),
    FOREIGN KEY (SELLER_ID) REFERENCES seller(ID)
    );