CREATE TABLE IF NOT EXISTS image (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IMG_PATH VARCHAR(255),
    VARIANT_ID INT,
    STORE_CATEGORY_ID INT,
    FOREIGN KEY (VARIANT_ID) REFERENCES variant (ID),
    FOREIGN KEY (STORE_CATEGORY_ID) REFERENCES store_category (ID)

    );