CREATE TABLE IF NOT EXISTS variant_optionvalue
(
    ID             INT AUTO_INCREMENT PRIMARY KEY,
    VARIANT_ID     INT,
    OPTIONVALUE_ID INT,
    FOREIGN KEY (VARIANT_ID) REFERENCES variant (ID),
    FOREIGN KEY (OPTIONVALUE_ID) REFERENCES optionvalue (ID)
);