CREATE TABLE IF NOT EXISTS PAYMENT_METHOD(
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    CART_NUMBER INT,
    NAME_ON_CARD VARCHAR(255),
    EXPIRATION_DATE VARCHAR(255),
    DEFAULT_PAYMENT BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (USER_ID) REFERENCES USER(ID)
);
