INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Blue', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Red', 1);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 2);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('RED', 3);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('MIN', 3);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('S', 4);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('M', 4);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('RED', 5);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('MIN', 5);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('XL', 6);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('XL', 6);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Pink', 7);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Green', 7);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('12cm', 8);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('10cm', 8);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Pink', 9);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Green', 9);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('12cm', 10);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('10cm', 10);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Pink', 11);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('Green', 11);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('12cm', 12);
INSERT IGNORE INTO OPTIONVALUE (value, option_id) VALUES ('10cm', 12);





