-- INSERT IGNORE INTO BULLET (NAME, PRODUCT_ID) VALUES
--     ('There"s been a murder on board the European Belle but whodunnit? Work on your detective skills with Talking Tables Murder Mystery on the Train Game Kit',1),
--     ('Replayable with 3 alternative endings!',1),
--     ('OCCASION - Perfect for a family games night, dinner party with friends or 1930"s themed party! It also makes a great Christmas or Birthday gifts for him, gifts for her, gifts for friends',1),
--     ('CONTENTS - Instruction booklet, Welcome speech, 12 x Place cards, 12x Name cards, 12x Trait cards, 12x Occupation cards, 12x Murder weapon props, 2x Police crime file, 28x Murder clues, 48x Accusation forms, 6x Solutions, 3x Award Trophies',1),
--     ('NSTRUCTIONS - Pick a colour ending and set up the coresponding props, clues and game cards. Follow the instructions to solve the mystery!',1),
--     ('AGE - Recommended for age 16+ and 5-13 players.',1),
--     ('QUALITY - Our products are designed with quality in mind and are strong, sturdy and made with care.',1);
-- INSERT IGNORE INTO BULLET (NAME, PRODUCT_ID) VALUES
--     ('There"s been a murder on board the European Belle but whodunnit? Work on your detective skills with Talking Tables Murder Mystery on the Train Game Kit',2),
--     ('Replayable with 3 alternative endings!',2),
--     ('OCCASION - Perfect for a family games night, dinner party with friends or 1930"s themed party! It also makes a great Christmas or Birthday gifts for him, gifts for her, gifts for friends',2),
--     ('CONTENTS - Instruction booklet, Welcome speech, 12 x Place cards, 12x Name cards, 12x Trait cards, 12x Occupation cards, 12x Murder weapon props, 2x Police crime file, 28x Murder clues, 48x Accusation forms, 6x Solutions, 3x Award Trophies',2),
--     ('NSTRUCTIONS - Pick a colour ending and set up the coresponding props, clues and game cards. Follow the instructions to solve the mystery!',2),
--     ('AGE - Recommended for age 16+ and 5-13 players.',2),
--     ('QUALITY - Our products are designed with quality in mind and are strong, sturdy and made with care.',2);
-- INSERT IGNORE INTO BULLET (NAME, PRODUCT_ID) VALUES
--     ('There"s been a murder on board the European Belle but whodunnit? Work on your detective skills with Talking Tables Murder Mystery on the Train Game Kit',3),
--     ('Replayable with 3 alternative endings!',3),
--     ('OCCASION - Perfect for a family games night, dinner party with friends or 1930"s themed party! It also makes a great Christmas or Birthday gifts for him, gifts for her, gifts for friends',3),
--     ('CONTENTS - Instruction booklet, Welcome speech, 12 x Place cards, 12x Name cards, 12x Trait cards, 12x Occupation cards, 12x Murder weapon props, 2x Police crime file, 28x Murder clues, 48x Accusation forms, 6x Solutions, 3x Award Trophies',2),
--     ('NSTRUCTIONS - Pick a colour ending and set up the coresponding props, clues and game cards. Follow the instructions to solve the mystery!',3),
--     ('AGE - Recommended for age 16+ and 5-13 players.',3),
--     ('QUALITY - Our products are designed with quality in mind and are strong, sturdy and made with care.',3);
--     INSERT IGNORE INTO BULLET (NAME, PRODUCT_ID) VALUES
--     ('There"s been a murder on board the European Belle but whodunnit? Work on your detective skills with Talking Tables Murder Mystery on the Train Game Kit',4),
--     ('Replayable with 3 alternative endings!',4),
--     ('OCCASION - Perfect for a family games night, dinner party with friends or 1930"s themed party! It also makes a great Christmas or Birthday gifts for him, gifts for her, gifts for friends',4),
--     ('CONTENTS - Instruction booklet, Welcome speech, 12 x Place cards, 12x Name cards, 12x Trait cards, 12x Occupation cards, 12x Murder weapon props, 2x Police crime file, 28x Murder clues, 48x Accusation forms, 6x Solutions, 3x Award Trophies',4),
--     ('NSTRUCTIONS - Pick a colour ending and set up the coresponding props, clues and game cards. Follow the instructions to solve the mystery!',4),
--     ('AGE - Recommended for age 16+ and 5-13 players.',4),
--     ('QUALITY - Our products are designed with quality in mind and are strong, sturdy and made with care.',4);