INSERT IGNORE INTO REVIEW (star, title,content,image01,image02,image03,image04,image05,video,verified_shop,verified_admin,create_at,update_at,customer_id,variant_id)
VALUES (5,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,1),
    (4,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,1),
    (3,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fast better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,1),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,1),
    (2,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,2),
    (2,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,2),
    (2,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,2),
    (4,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,2),
     (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,2),
     (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,1),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,3),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,4),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,5),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,6),
    (1,'I wish that I had found these before I spent 1000"s on doctors and Physical therapy',
    'Seriously these are the best things I''ve found. They have helped my plantar fascitis better than the Shot the foot doctor gave, and the many physical therapy appointments which cost me every time I went. I wish I had found them before all that. Even after all that I still had pain, it was better, but not 100%, these inserts have helped me profoundly. Please note that they do not work in all shoes, but so far I''ve only had one pair of my shoes that they didn''t work in. I''ll be chucking those. They''ve worked in dress shoes, and my Puma workout shoes along with my Keen hiking shoes. So if they don''t work for you, try them in a different shoe. I bet they will work in any flat shoe with little or no arch support. Give them a shot if you suffer as I did.',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',
    'https://m.media-amazon.com/images/I/71kp5w3wNVL.__AC_SX300_SY300_QL70_FMwebp_.jpg',null,1,1,NOW(), NOW(),1,7)
